### ISSUE TITLE
Comparison with and without TensorFlow Lite XNNPACK delegate

### ISSUE THREAD

**Issue by Gaozhongpai** [ilialan/yolov5_object_detection_medaipipe#1]
Thank you for this project. I use `yolov5s.pt` to convert to `yolov5s_640_fp16.tflite`. I try with and without XNNPACK delegate. There is no difference, and both are very slow (less than 5 FPS). For yolov5s_640,  `num_boxes: 25200`. I wonder whether the XNNPACK takes any effect here. Thanks

![image](https://github.com/ilialan/yolov5_object_detection_medaipipe/assets/4093624/d893342b-57ce-47f9-bdf5-7d59c1afd2e9)

**Comment by ilialan** [comment]
Hey, thank you for this comment.
Did you try to build it with a proper key? It should be something like this:
--define tflite_with_xnnpack=true
Having said that, I also suggest you to retrain your network with a smaller image size of something like 320x320, and it will run considerably faster.
